version: '3'

services:
  postgres:
    image: kartoza/postgis:11.0-2.5
    environment:
      - POSTGRES_DB=opendatacube
      - POSTGRES_PASSWORD=opendatacubepassword
      - POSTGRES_USER=opendatacube
    ports:
      - 5432:5432
    restart: always
  
  jupyter:
    build: .
    environment:
      - DB_HOSTNAME=postgres
      - DB_USERNAME=opendatacube
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=opendatacube
      - AWS_REQUEST_PAYER=requester
    ports:
      - "80:8888"
    volumes:
      - ./scripts:/opt/odc/scripts
      - ./products:/opt/odc/products
      - ./data:/opt/odc/data
      - ./notebooks:/notebooks
    restart: always
    command: jupyter notebook --allow-root --ip="0.0.0.0" --NotebookApp.token='secretpassword'
